// Tap hold configuration
#undef TAPPING_TERM
#define TAPPING_TERM 140
#define TAPPING_TERM_PER_KEY
#define FLOW_TAP_TERM 160
#define PERMISSIVE_HOLD
#define CHORDAL_HOLD
#define SPECULATIVE_HOLD
#define SPECULATIVE_HOLD_ONE_KEY
#define SPECULATIVE_HOLD_FLOW_TERM 200

#define DUMMY_MOD_NEUTRALIZER_KEYCODE KC_RCTL
#define MODS_TO_NEUTRALIZE \
  { MOD_BIT(KC_LALT), MOD_BIT(KC_LGUI), MOD_BIT(KC_RGUI) }

#define USB_SUSPEND_WAKEUP_DELAY 0

#define SERIAL_NUMBER "yXMjP/x9QE0x"
#define LAYER_STATE_16BIT
#define COMBO_COUNT 44

// Use both Ctrl keys to activate Command feature
#define IS_COMMAND() (get_mods() == MOD_MASK_CTRL)

// Hold Shift on CAPS_WORD to invert the shift state
#define CAPS_WORD_INVERT_ON_SHIFT

#define ONESHOT_TIMEOUT 5000

// getreuer cyclotab
#define CYCLOTAB_TIMEOUT 700
#define CYCLOTAB_KEYS C(KC_TAB), A(KC_TAB)

// getreuer super leader
#define SUPER_LEADER_NO_INIT_TIMEOUT
#define SUPER_LEADER_TIMEOUT  1000

// mouse
#define ORBITAL_MOUSE_SPEED_CURVE {20, 21, 26, 33, 43, 57, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70}

#define LUMINO_TRANSITION 850
#define LUMINO_BOOT_COLOR RGB_WHITE
#define LUMINO_NO_EEPROM

#define PALETTEFX_ENABLE_ALL_EFFECTS
#define PALETTEFX_ENABLE_ALL_PALETTES


// Since we have PaletteFx, disable most built-in RGB Matrix effects.
#  undef ENABLE_RGB_MATRIX_ALPHAS_MODS
#  undef ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#  undef ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
#  undef ENABLE_RGB_MATRIX_BREATHING
#  undef ENABLE_RGB_MATRIX_BAND_SAT
#  undef ENABLE_RGB_MATRIX_BAND_VAL
#  undef ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
#  undef ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
#  undef ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT
#  undef ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#  undef ENABLE_RGB_MATRIX_CYCLE_ALL
#  undef ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#  undef ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
#  undef ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#  undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN
#  undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#  undef ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
#  undef ENABLE_RGB_MATRIX_CYCLE_SPIRAL
#  undef ENABLE_RGB_MATRIX_DUAL_BEACON
#  undef ENABLE_RGB_MATRIX_RAINBOW_BEACON
#  undef ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
#  undef ENABLE_RGB_MATRIX_FLOWER_BLOOMING
#  undef ENABLE_RGB_MATRIX_RAINDROPS
#  undef ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#  undef ENABLE_RGB_MATRIX_HUE_BREATHING
#  undef ENABLE_RGB_MATRIX_HUE_PENDULUM
#  undef ENABLE_RGB_MATRIX_HUE_WAVE
#  undef ENABLE_RGB_MATRIX_PIXEL_FRACTAL
#  undef ENABLE_RGB_MATRIX_PIXEL_FLOW
#  undef ENABLE_RGB_MATRIX_PIXEL_RAIN
#  undef ENABLE_RGB_MATRIX_STARLIGHT
#  undef ENABLE_RGB_MATRIX_STARLIGHT_DUAL_SAT
#  undef ENABLE_RGB_MATRIX_RIVERFLOW

#  undef ENABLE_RGB_MATRIX_DIGITAL_RAIN

#  undef ENABLE_RGB_MATRIX_SOLID_REACTIVE
#  undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
#  undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
#  undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
#  undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
#  undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
#  undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
#  undef ENABLE_RGB_MATRIX_SPLASH
#  undef ENABLE_RGB_MATRIX_MULTISPLASH
#  undef ENABLE_RGB_MATRIX_SOLID_SPLASH
#  undef ENABLE_RGB_MATRIX_SOLID_MULTISPLASH

