CONSOLE_ENABLE = no
SPACE_CADET_ENABLE = no

ORYX_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
TAP_DANCE_ENABLE = yes
STENO_ENABLE = yes
STENO_PROTOCOL = geminipr
KEYBOARD_SHARED_EP = yes
CAPS_WORD_ENABLE = yes
REPEAT_KEY_ENABLE = yes
COMBO_ENABLE = yes
DYNAMIC_TAPPING_TERM_ENABLE = yes
LAYER_LOCK_ENABLE = yes

SWAP_HANDS_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
REPEAT_KEY_ENABLE = yes
AUDIO_ENABLE = yes
MOUSE_ENABLE = yes
DEFERRED_EXEC_ENABLE = yes